apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapsel-service
  namespace: demo
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kapsel-service-agent-api
  namespace: demo
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["agent-api"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kapsel-service-agent-api
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: kapsel-service
    namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kapsel-service-agent-api
