[package]
name = "kapsel-installer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false
build = "build.rs"

[dependencies]
base64 = "0.23.1"
http.workspace = true
kapsel.workspace = true
rustix = { workspace = true, features = ["fs", "process", "rand", "std"] }
serde.workspace = true
serde_json.workspace = true
serde-saphyr = { version = "1.1.0", default-features = false, features = ["deserialize"] }
sha2.workspace = true

[build-dependencies]
rustix = { workspace = true, features = ["fs", "std"] }
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true
